---
dependencies: []

galaxy_info:
  author: Rauny Moreira
  description: Docker for Linux.
  company: "4Linux"
  license: "license (GPL)"
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - 8
    - name: Fedora
      versions:
        - all
  galaxy_tags:
    - web
    - system
    - containers
    - docker
    - orchestration
    - compose
    - server
