# my global config
global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'monitoring'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.

rule_files:
  - /etc/prometheus/rules/*.rules

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
    - targets: ['10.23.4.11:8080']

  - job_name: 'node-exporter'
    static_configs:
    - targets: ['10.23.4.11:9100']

  - job_name: 'apache-exporter'
    static_configs:
    - targets: ['10.23.4.11:9117']
